import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';import {btree_gist} from '@electric-sql/pglite/contrib/btree_gist';import {randomUUID} from 'node:crypto';
test('manual ledger fences retries, refund limits, reversals, ownership and MFA without provider verification',async()=>{const db=new PGlite({extensions:{btree_gist}}),a=randomUUID(),b=randomUUID();try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;grant usage on schema auth to authenticated;insert into auth.users values('${a}'),('${b}');`);
 for(const file of ['schema','calendar_controls','booking_transactions'])await db.exec(await readFile(new URL(`../database/${file}.sql`,import.meta.url),'utf8'));
 const login=async(id,aal='aal2')=>db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${id}',false);select set_config('request.jwt.claims','{"aal":"${aal}"}',false);`);await login(a);
 const p=(await db.query(`insert into ts_properties(owner_id,name,weekday_cents,weekend_cents) values($1,'Synthetic ledger',5600,7000) returning id`,[a])).rows[0].id,booking=(await db.query(`insert into ts_reservations(owner_id,property_id,guest,arrival,departure,guests) values($1,$2,'Synthetic','2026-10-01','2026-10-04',1) returning id`,[a,p])).rows[0].id;
 const save=async(expected,kind,amount,related=null,request=randomUUID(),ref=randomUUID(),date='2026-10-01')=>(await db.query('select ts_record_booking_transaction($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) as id',[booking,expected,request,kind,amount,related,'channel',date,ref,'Synthetic checked record'])).rows[0].id;
 const key=randomUUID(),ref='receipt-1',payment=await save(0,'payment',10000,null,key,ref);assert.equal(await save(0,'payment',10000,null,key,ref),payment);await assert.rejects(()=>save(0,'payment',9000,null,key,ref),/already used/);await assert.rejects(()=>save(0,'payment',100),/Transactions changed/);await assert.rejects(()=>save(1,'payment',100,null,randomUUID(),' RECEIPT-1 '),e=>e.code==='23505');await assert.rejects(()=>save(1,'payment',100,null,randomUUID(),'future','2099-01-01'),/future payments/);
 const refund=await save(1,'refund',6000,payment);await assert.rejects(()=>save(2,'refund',4001,payment),/Refund exceeds/);await assert.rejects(()=>save(2,'reversal',10000,payment),/Reverse active refund/);await assert.rejects(()=>save(2,'reversal',5000,refund),/entire record/);await save(2,'reversal',6000,refund);await assert.rejects(()=>save(3,'reversal',6000,refund),/active transaction/);const fullRefund=await save(3,'refund',10000,payment);assert.equal((await db.query('select * from ts_booking_transactions')).rows.length,4);
 await assert.rejects(()=>db.query("insert into ts_booking_transactions(owner_id,booking_id,sequence,request_id,kind,amount_cents,method,occurred_on,reference,note,evidence) values($1,$2,5,$3,'payment',100,'cash','2026-10-01','fake-proof','Synthetic','processor_verified')",[a,booking,randomUUID()]),e=>e.code==='23514');
 await assert.rejects(()=>db.query("update ts_booking_transactions set evidence='processor_verified'"),e=>e.code==='42501');await assert.rejects(()=>db.query('delete from ts_booking_transactions'),e=>e.code==='42501');
 await login(b);assert.equal((await db.query('select * from ts_booking_transactions')).rows.length,0);await assert.rejects(()=>save(4,'payment',100),/Booking unavailable/);await login(a,'aal1');assert.equal((await db.query('select * from ts_booking_transactions')).rows.length,0);await assert.rejects(()=>save(4,'payment',100),/Authenticator required/);
 await login(a);await db.query("update ts_reservations set status='cancelled' where id=$1",[booking]);await assert.rejects(()=>save(4,'payment',100),/confirmed booking/);await assert.rejects(()=>save(4,'refund',1,payment),/Refund exceeds/);await save(4,'reversal',10000,fullRefund);await save(5,'refund',5000,payment);assert.equal((await db.query('select * from ts_booking_transactions')).rows.length,6);
 await db.exec('reset role;set role anon');await assert.rejects(()=>db.query('select * from ts_booking_transactions'),e=>e.code==='42501');await assert.rejects(()=>save(4,'payment',100),e=>e.code==='42501');
 }finally{await db.close();}});
