import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {btree_gist} from '@electric-sql/pglite/contrib/btree_gist';
test('actual schema rejects foreign accounts, overlap and invalid occupancy',async()=>{
 const db=new PGlite({extensions:{btree_gist}});
 const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002';
 await db.exec(`create role anon; create role authenticated; create role service_role; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema auth to authenticated; grant execute on function auth.uid() to authenticated; insert into auth.users values('${a}'),('${b}');`);
 await db.exec(await readFile(new URL('../database/schema.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../database/guest_experience.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../database/display_devices.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../database/display_personalization.sql',import.meta.url),'utf8'));
 const login=async id=>{await db.exec(`reset role; set role authenticated; select set_config('request.jwt.claim.sub','${id}',false);`);};
 await login(a);
 const result=await db.query(`insert into ts_properties(owner_id,name,weekday_cents,weekend_cents) values($1,'Pilot room',5600,7000) returning id`,[a]);const p=result.rows[0].id;
 const book=async(owner,arrival,departure,guests=2)=>db.query(`insert into ts_reservations(owner_id,property_id,guest,arrival,departure,guests) values($1,$2,'Synthetic guest',$3,$4,$5) returning id`,[owner,p,arrival,departure,guests]);
 await db.query(`insert into ts_guest_displays(owner_id,property_id,title) values($1,$2,'Welcome')`,[a,p]);
 const device=await db.query(`insert into ts_display_devices(owner_id,property_id,name,token_hash) values($1,$2,'Synthetic TV',$3) returning id`,[a,p,'a'.repeat(64)]);
 await assert.rejects(()=>db.query(`update ts_display_devices set token_hash=$1 where id=$2`,['b'.repeat(64),device.rows[0].id]),e=>e.code==='42501');
 const first=await book(a,'2026-10-05','2026-10-07');
 await assert.rejects(()=>book(a,'2026-10-06','2026-10-08'),e=>e.code==='23P01');
 await book(a,'2026-10-07','2026-10-09');
 await assert.rejects(()=>book(a,'2026-10-10','2026-10-11',3),/Maximum occupancy/);
 await login(b);
 assert.equal((await db.query('select * from ts_display_devices')).rows.length,0);
 assert.equal((await db.query(`update ts_display_devices set revoked=true where id=$1 returning id`,[device.rows[0].id])).rows.length,0);
 await assert.rejects(()=>db.query(`insert into ts_display_devices(owner_id,property_id,name,token_hash) values($1,$2,'Foreign TV',$3)`,[b,p,'c'.repeat(64)]),e=>e.code==='23503');
 assert.equal((await db.query('select * from ts_guest_displays')).rows.length,0);
 await assert.rejects(()=>db.query(`insert into ts_guest_displays(owner_id,property_id,title) values($1,$2,'Foreign') on conflict(property_id) do update set title=excluded.title`,[b,p]),e=>e.code==='42501');
 assert.equal((await db.query('select * from ts_properties')).rows.length,0);
 assert.equal((await db.query('select * from ts_reservations')).rows.length,0);
 await assert.rejects(()=>book(b,'2026-10-10','2026-10-11'),/Listing unavailable/);
 await assert.rejects(()=>db.query(`insert into ts_message_templates(owner_id,name,body) values($1,'Foreign','No')`,[a]),e=>e.code==='42501');
 assert.equal((await db.query(`update ts_reservations set status='cancelled' where id=$1 returning id`,[first.rows[0].id])).rows.length,0);
 await login(a);
 await db.query(`update ts_display_devices set revoked=true where id=$1`,[device.rows[0].id]);
 await assert.rejects(()=>db.query(`update ts_display_devices set revoked=false where id=$1`,[device.rows[0].id]),e=>e.code==='42501');
 await assert.rejects(()=>db.query(`update ts_properties set owner_id=$1 where id=$2`,[b,p]),e=>['42501','23503'].includes(e.code));
 await db.query(`update ts_reservations set status='cancelled' where id=$1`,[first.rows[0].id]);await book(a,'2026-10-05','2026-10-07');
 await db.exec('reset role; set role anon;');await assert.rejects(()=>db.query('select * from ts_properties'),e=>e.code==='42501');
 await assert.rejects(()=>db.query('select * from ts_display_devices'),e=>e.code==='42501');
 await db.close();
});
