import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {btree_gist} from '@electric-sql/pglite/contrib/btree_gist';
test('actual schema rejects foreign accounts, overlap and invalid occupancy',async()=>{
 const db=new PGlite({extensions:{btree_gist}});
 const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002';
 await db.exec(`create role anon; create role authenticated; create role service_role; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; create function auth.jwt() returns jsonb language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb $$; grant usage on schema auth to authenticated; grant execute on function auth.jwt() to authenticated; grant execute on function auth.uid() to authenticated; insert into auth.users values('${a}'),('${b}'),('3f03551d-89de-4214-aa7a-db7a86fe1735');`);
 await db.exec(await readFile(new URL('../database/schema.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../database/guest_experience.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../database/display_devices.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../database/display_personalization.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../database/display_pairing.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../database/calendar_controls.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../database/host_mfa.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../database/door_locks.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../database/guest_phone_code.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../database/multi_brand_locks.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../database/ttlock_accounts.sql',import.meta.url),'utf8'));
 const login=async id=>{await db.exec(`reset role; set role authenticated; select set_config('request.jwt.claims','{"aal":"aal2"}',false); select set_config('request.jwt.claim.sub','${id}',false);`);};
 await db.exec(`insert into ts_ttlock_accounts(owner_id,provider_uid,status,sealed_tokens,expires_at) values('${a}','123','connected','synthetic-cipher',now()+interval '1 day');`);
 assert.equal((await db.query('select * from ts_claim_ttlock_connect($1)',[a])).rows.length,1);
 assert.equal((await db.query('select * from ts_claim_ttlock_connect($1)',[a])).rows.length,0);
 await login(a);
 assert.equal((await db.query('select owner_id,status from ts_ttlock_accounts')).rows.length,1);
 await assert.rejects(()=>db.query('select sealed_tokens from ts_ttlock_accounts'),e=>e.code==='42501');
 await assert.rejects(()=>db.query(`select * from ts_claim_ttlock_connect($1)`,[a]),e=>e.code==='42501');
 await login(b);assert.equal((await db.query('select owner_id,status from ts_ttlock_accounts')).rows.length,0);
 await login(a);
 const result=await db.query(`insert into ts_properties(owner_id,name,weekday_cents,weekend_cents) values($1,'Pilot room',5600,7000) returning id`,[a]);const p=result.rows[0].id;
 // Password-only and missing assurance claims cannot read or write any host table.
 for(const claims of ['{"aal":"aal1"}','{}']){
  await db.query("select set_config('request.jwt.claims',$1,false)",[claims]);
  for(const table of ['ts_properties','ts_reservations','ts_rates','ts_message_templates','ts_guest_displays','ts_display_devices','ts_locks','ts_lock_assignments'])assert.equal((await db.query(`select * from ${table}`)).rows.length,0);
  assert.equal((await db.query('select owner_id,status from ts_ttlock_accounts')).rows.length,0);
  await assert.rejects(()=>db.query(`insert into ts_message_templates(owner_id,name,body) values($1,'Blocked','No')`,[a]),e=>e.code==='42501');
  assert.equal((await db.query(`update ts_properties set name='Blocked' where id=$1 returning id`,[p])).rows.length,0);
 }
 await login(a);
 const lock=await db.query(`insert into ts_locks(owner_id,name,provider_lock_id) values($1,'Synthetic room lock','123') returning id`,[a]);
 await assert.rejects(()=>db.query(`update ts_locks set capabilities='{"online_codes":true}' where id=$1`,[lock.rows[0].id]),e=>e.code==='42501');
 await assert.rejects(()=>db.query(`insert into ts_lock_connections(id,owner_id) values(gen_random_uuid(),$1)`,[a]),e=>e.code==='42501');
 const route=await db.query(`insert into ts_lock_assignments(owner_id,property_id,lock_id,purpose) values($1,$2,$3,'room') returning id`,[a,p,lock.rows[0].id]);
 await login(b);
 assert.equal((await db.query('select * from ts_locks')).rows.length,0);
 assert.equal((await db.query('select * from ts_lock_assignments')).rows.length,0);
 await assert.rejects(()=>db.query(`insert into ts_lock_assignments(owner_id,property_id,lock_id,purpose) values($1,$2,$3,'entrance')`,[b,p,lock.rows[0].id]),e=>e.code==='23503');
 assert.equal((await db.query(`delete from ts_lock_assignments where id=$1 returning id`,[route.rows[0].id])).rows.length,0);
 await login(a);
 await db.query("select set_config('request.jwt.claims',$1,false)",['{"aal":"aal1"}']);
 assert.equal((await db.query('select * from ts_locks')).rows.length,0);
 assert.equal((await db.query(`delete from ts_lock_assignments where id=$1 returning id`,[route.rows[0].id])).rows.length,0);
 await assert.rejects(()=>db.query(`insert into ts_locks(owner_id,name) values($1,'Blocked')`,[a]),e=>e.code==='42501');
 await login(a);
 await db.query(`delete from ts_lock_assignments where id=$1`,[route.rows[0].id]);
 assert.equal((await db.query('select * from ts_lock_assignments')).rows.length,0);
 const book=async(owner,arrival,departure,guests=2)=>db.query(`insert into ts_reservations(owner_id,property_id,guest,arrival,departure,guests) values($1,$2,'Synthetic guest',$3,$4,$5) returning id`,[owner,p,arrival,departure,guests]);
 await db.query(`insert into ts_guest_displays(owner_id,property_id,title) values($1,$2,'Welcome')`,[a,p]);
 const device=await db.query(`insert into ts_display_devices(owner_id,property_id,name,token_hash) values($1,$2,'Synthetic TV',$3) returning id`,[a,p,'a'.repeat(64)]);
 await assert.rejects(()=>db.query(`update ts_display_devices set token_hash=$1 where id=$2`,['b'.repeat(64),device.rows[0].id]),e=>e.code==='42501');
 const first=await book(a,'2026-10-05','2026-10-07');
 await db.query(`update ts_reservations set guest_phone_last4='0042' where id=$1`,[first.rows[0].id]);
 assert.equal((await db.query(`select guest_phone_last4 from ts_reservations where id=$1`,[first.rows[0].id])).rows[0].guest_phone_last4,'0042');
 await assert.rejects(()=>db.query(`update ts_reservations set guest_phone_last4='12345' where id=$1`,[first.rows[0].id]),e=>e.code==='23514');
 await assert.rejects(()=>book(a,'2026-10-06','2026-10-08'),e=>e.code==='23P01');
 const second=await book(a,'2026-10-07','2026-10-09');
 await assert.rejects(()=>db.query(`update ts_reservations set arrival='2026-10-06' where id=$1`,[second.rows[0].id]),e=>e.code==='23P01');
 const block=await db.query(`insert into ts_reservations(owner_id,property_id,guest,arrival,departure,guests,kind,status) values($1,$2,'Maintenance','2026-10-10','2026-10-12',1,'block','blocked') returning id`,[a,p]);
 await assert.rejects(()=>book(a,'2026-10-11','2026-10-13'),e=>e.code==='23P01');
 await assert.rejects(()=>db.query(`insert into ts_reservations(owner_id,property_id,guest,arrival,departure,guests,kind,status) values($1,$2,'Owner stay','2026-10-06','2026-10-07',1,'block','blocked')`,[a,p]),e=>e.code==='23P01');
 await db.query(`update ts_reservations set status='cancelled' where id=$1`,[block.rows[0].id]);
 await book(a,'2026-10-10','2026-10-12');
 await assert.rejects(()=>book(a,'2026-10-10','2026-10-11',3),/Maximum occupancy/);
 await login(b);
 assert.equal((await db.query('select * from ts_display_devices')).rows.length,0);
 assert.equal((await db.query(`update ts_display_devices set revoked=true where id=$1 returning id`,[device.rows[0].id])).rows.length,0);
 await assert.rejects(()=>db.query(`insert into ts_display_devices(owner_id,property_id,name,token_hash) values($1,$2,'Foreign TV',$3)`,[b,p,'c'.repeat(64)]),e=>e.code==='23503');
 assert.equal((await db.query('select * from ts_guest_displays')).rows.length,0);
 await assert.rejects(()=>db.query(`insert into ts_guest_displays(owner_id,property_id,title) values($1,$2,'Foreign') on conflict(property_id) do update set title=excluded.title`,[b,p]),e=>e.code==='42501');
 assert.equal((await db.query('select * from ts_properties')).rows.length,0);
 assert.equal((await db.query('select * from ts_reservations')).rows.length,0);
 await assert.rejects(()=>book(b,'2026-10-10','2026-10-11'),/Listing unavailable/);
 await assert.rejects(()=>db.query(`insert into ts_message_templates(owner_id,name,body) values($1,'Foreign','No')`,[a]),e=>e.code==='42501');
 assert.equal((await db.query(`update ts_reservations set status='cancelled' where id=$1 returning id`,[first.rows[0].id])).rows.length,0);
 await login(a);
 await db.query(`update ts_display_devices set revoked=true where id=$1`,[device.rows[0].id]);
 await assert.rejects(()=>db.query(`update ts_display_devices set revoked=false where id=$1`,[device.rows[0].id]),e=>e.code==='42501');
 await assert.rejects(()=>db.query(`update ts_properties set owner_id=$1 where id=$2`,[b,p]),e=>['42501','23503'].includes(e.code));
 await db.query(`update ts_reservations set status='cancelled' where id=$1`,[first.rows[0].id]);await book(a,'2026-10-05','2026-10-07');
 await login('3f03551d-89de-4214-aa7a-db7a86fe1735');
 await db.exec("select set_config('request.jwt.claims','{\"aal\":\"aal1\"}',false)");
 const own=await db.query(`insert into ts_properties(owner_id,name,weekday_cents,weekend_cents) values($1,'Exempt pilot',5600,7000) returning id`,['3f03551d-89de-4214-aa7a-db7a86fe1735']);
 assert.equal((await db.query('select * from ts_properties')).rows.length,1);
 assert.equal((await db.query(`update ts_properties set name='Forbidden' where id=$1 returning id`,[p])).rows.length,0);
 await login(a);
 assert.equal((await db.query(`select * from ts_properties where id=$1`,[own.rows[0].id])).rows.length,0);
 await db.exec('reset role; set role anon;');await assert.rejects(()=>db.query('select * from ts_properties'),e=>e.code==='42501');
 await assert.rejects(()=>db.query('select * from ts_display_devices'),e=>e.code==='42501');
 await db.close();
});
