import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';import {btree_gist} from '@electric-sql/pglite/contrib/btree_gist';import {randomUUID} from 'node:crypto';
test('transaction imports are atomic, ordered, retry safe, linked to owned bookings, bounded by payments and protected by MFA',async()=>{
 const db=new PGlite({extensions:{btree_gist}}),a=randomUUID(),b=randomUUID();try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;grant usage on schema auth to authenticated;insert into auth.users values('${a}'),('${b}');`);
 for(const file of ['schema','calendar_controls','guest_phone_code','turnover_tasks','turnover_checklists','message_schedules','booking_imports','booking_transactions','transaction_imports'])await db.exec(await readFile(new URL(`../database/${file}.sql`,import.meta.url),'utf8'));
 const login=async(id,aal='aal2')=>db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${id}',false);select set_config('request.jwt.claims','{"aal":"${aal}"}',false);`);await login(a);
 const p=(await db.query(`insert into ts_properties(owner_id,name,weekday_cents,weekend_cents) values($1,'Transaction import',5600,7000) returning id`,[a])).rows[0].id;
 const book={external_id:'B1',guest:'Guest',arrival:'2026-11-01',departure:'2026-11-03',guests:2,status:'confirmed',note:'',guest_phone_last4:null},second={...book,external_id:'B2',arrival:'2026-11-04',departure:'2026-11-06'};await db.query('select ts_import_bookings($1,$2,$3)',[p,'uplisting',JSON.stringify([book,second])]);
 const row={transaction_id:'P1',booking_id:'B1',guest:'Guest',arrival:book.arrival,departure:book.departure,guests:2,kind:'payment',amount_cents:20001,currency:'USD',occurred_on:'2026-10-01',method:'channel',reference:'PAY-REF',parent_transaction_id:''},refund={...row,transaction_id:'R1',kind:'refund',amount_cents:5000,occurred_on:'2026-10-02',reference:'REFUND-REF',parent_transaction_id:'P1'};
 const save=async(rows=[row],property=p,source='uplisting')=>(await db.query('select ts_import_transactions($1,$2,$3) as result',[property,source,JSON.stringify(rows)])).rows[0].result;
 assert.deepEqual(await save([refund,row]),{added:2,skipped:0});let ledger=(await db.query('select * from ts_booking_transactions order by sequence')).rows;assert.equal(ledger[0].kind,'payment');assert.equal(ledger[1].related_id,ledger[0].id);assert.equal(ledger[0].evidence,'host_recorded');
 assert.deepEqual(await save([row,refund]),{added:0,skipped:2});await assert.rejects(()=>save([{...row,amount_cents:25000}]),/different saved details/);
 const before=ledger.length;await assert.rejects(()=>save([{...row,transaction_id:'P2',reference:'Second-payment'},{...refund,transaction_id:'R2',reference:'Too-much',amount_cents:15002}]),/Refund exceeds/);assert.equal((await db.query('select * from ts_booking_transactions')).rows.length,before);assert.equal((await db.query('select * from ts_transaction_imports')).rows.length,before);
 const first=ledger[0],last=ledger[1];await db.query("update ts_reservations set status='cancelled' where id=$1",[first.booking_id]);assert.deepEqual(await save([{...refund,transaction_id:'R3',reference:'Later-refund',amount_cents:1000}]),{added:1,skipped:0});
 await assert.rejects(()=>save([{...row,transaction_id:'P3',reference:'Cancelled-payment'}]),/confirmed booking/);
 await assert.rejects(()=>save([{...refund,transaction_id:'R4',reference:'Early',occurred_on:'2026-09-30'}]),/date precedes/);
 await assert.rejects(()=>save([{...refund,transaction_id:'R4',booking_id:'B2',arrival:second.arrival,departure:second.departure,reference:'Wrong-booking'}]),/same booking/);
 for(const patch of [{currency:'EUR'},{amount_cents:0},{amount_cents:1.5},{occurred_on:'9999-12-31'},{kind:'reversal'},{method:'card'},{owner_id:b},{guest:'Changed'}])await assert.rejects(()=>save([{...row,transaction_id:'BAD',reference:'Bad',...patch}]));
 await assert.rejects(()=>save([row,row]),/Repeated/);await assert.rejects(()=>save([{...row,transaction_id:'P4',reference:'pay-ref'}]),/reference already exists/);
 const seq=(await db.query('select max(sequence) as n from ts_booking_transactions where booking_id=$1',[first.booking_id])).rows[0].n;await db.query('select ts_record_booking_transaction($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[first.booking_id,seq,randomUUID(),'reversal',5000,last.id,'channel','2026-10-03','Correction-ref','Synthetic correction']);
 assert.deepEqual(await save([refund,row]),{added:0,skipped:2});await assert.rejects(()=>save([{...refund,transaction_id:'R5',reference:'New-after-manual'}]),/manual transaction history/);
 await assert.rejects(()=>db.query('update ts_transaction_imports set source=$1',['other']),e=>e.code==='42501');await db.exec('reset role');await assert.rejects(()=>db.query('delete from ts_transaction_imports'),/immutable/);
 await login(b);assert.equal((await db.query('select * from ts_transaction_imports')).rows.length,0);await assert.rejects(()=>save(),/owned listing/);
 await login(a,'aal1');assert.equal((await db.query('select * from ts_transaction_imports')).rows.length,0);await assert.rejects(()=>save());await db.exec('reset role;set role anon');await assert.rejects(()=>save(),e=>e.code==='42501');await assert.rejects(()=>db.query('select * from ts_transaction_imports'),e=>e.code==='42501');
 }finally{await db.close();}
});
