import React,{useState} from 'react';
import {ruleQuote,rulesFor} from './pricing-rules.mjs';import {QuoteBreakdown} from './pricing-rules.jsx';import {todayInZone} from './pricing-model.mjs';
import {db} from './backend.js';import {money} from './model.mjs';import {amountFields,centsInput,validateAmounts,financialMatches} from './booking-financials.mjs';
export function BookingFinancials({reservation,property,rates,pricingRules=[],history=[],busy,onAction}){
 const [open,setOpen]=useState(false),[error,setError]=useState(''),latest=[...history].sort((a,b)=>b.revision-a.revision)[0],[values,setValues]=useState(()=>Object.fromEntries(Object.keys(amountFields).map(k=>[k,((latest?.[k]||0)/100).toFixed(2)]))),[note,setNote]=useState(''),[quoteDate,setQuoteDate]=useState(()=>todayInZone(property?.timezone||'UTC')),[draftPreview,setDraftPreview]=useState(null);
 if(reservation.kind==='block')return null;const matched=financialMatches(latest,reservation);let totals;try{totals=validateAmounts(Object.fromEntries(Object.entries(values).map(([k,v])=>[k,centsInput(v)])));}catch{}
 const confirmed=reservation.status==='confirmed';
 async function save(e){e.preventDefault();try{const amounts=Object.fromEntries(Object.entries(values).map(([k,v])=>[k,centsInput(v)]));validateAmounts(amounts);setError('');await onAction(async()=>{const {error}=await db.rpc('ts_save_booking_financials',{p_booking:reservation.id,p_expected:latest?.revision||0,p_property:reservation.property_id,p_arrival:reservation.arrival,p_departure:reservation.departure,p_guests:reservation.guests,p_amounts:amounts,p_note:note});if(error)throw Error(error.message);});}catch(e){setError(e.message);}}
 function draft(){try{setDraftPreview(ruleQuote(property,reservation.arrival,reservation.departure,reservation.guests,rates,rulesFor(pricingRules,property.id),quoteDate));setError('');}catch(e){setDraftPreview(null);setError(e.message);}} function useDraft(){setValues(v=>({...v,...Object.fromEntries(['accommodation_cents','discount_cents','cleaning_cents','extra_guest_cents'].map(k=>[k,(draftPreview.amounts[k]/100).toFixed(2)]))}));setDraftPreview(null);}
 return <><button className="link" disabled={busy} onClick={()=>setOpen(!open)}>{open?'Close amounts':latest?'Booking amounts':'Add booking amounts'}</button>{open&&<div className="reservation-editor booking-amounts"><h3>Saved booking charges</h3><p>USD · whole-stay amounts. These records track agreed charges; they do not charge the guest or record collected payments.</p>{latest&&<p>Revision {latest.revision} · {money(Number(latest.total_cents)/100)} total including taxes · {matched?'Matches this booking':'Needs review: booking details changed'}</p>}{confirmed&&<form onSubmit={save}><label>Booking / quote date for draft<input type="date" value={quoteDate} onChange={e=>{setQuoteDate(e.target.value);setDraftPreview(null);}}/></label><button className="small" type="button" disabled={busy} onClick={draft}>Preview current pricing rules</button>{draftPreview&&<><QuoteBreakdown preview={draftPreview}/><button type="button" disabled={busy} onClick={useDraft}>Use this draft in charge fields</button></>}<p>Review the agreed amount before saving. Using this draft replaces accommodation, discount, cleaning and extra guest charges; other fees, taxes and host channel fees retain their entered values.</p>{Object.entries(amountFields).map(([key,label])=><label key={key}>{label} ($)<input required type="number" min="0" max="10000000" step="0.01" value={values[key]} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))}/></label>)}{totals&&<p><strong>Guest charge total {money(totals.total/100)}</strong><br/>Accommodation after discount {money(totals.net/100)} · guest fees {money(totals.fees/100)} · taxes {money(centsInput(values.tax_cents)/100)}. Host channel fees are recorded separately.</p>}<label>Reason / reference for this revision<textarea maxLength="1000" value={note} onChange={e=>setNote(e.target.value)} required placeholder="Agreed booking total, correction or amended stay"/></label><label className="financial-confirm"><input type="checkbox" required/>I checked these amounts against the agreed booking charges.</label><button disabled={busy}>Save charge revision</button>{error&&<p role="alert">{error}</p>}</form>}{!confirmed&&<p>This booking is cancelled. Saved revisions remain available for review and are excluded from booked-charge reports. Review recorded payments and completed refunds under Payments / refunds.</p>}{history.length>0&&<details><summary>Charge history ({history.length})</summary>{[...history].sort((a,b)=>b.revision-a.revision).map(h=><article key={h.id}><strong>Revision {h.revision} · {money(Number(h.total_cents)/100)}</strong><p>{h.arrival} → {h.departure} · {h.guests} guests · {new Date(h.created_at).toLocaleString()}</p><p>{Object.entries(amountFields).map(([k,label])=>`${label}: ${money(Number(h[k])/100)}`).join(' · ')}</p><p>{h.note}</p></article>)}</details>}</div>}</>;
}
