import React,{useState} from 'react';
import {db} from './backend.js';import {quote,money} from './model.mjs';import {amountFields,centsInput,validateAmounts,financialMatches} from './booking-financials.mjs';
export function BookingFinancials({reservation,property,rates,history=[],busy,onAction}){
 const [open,setOpen]=useState(false),[error,setError]=useState(''),latest=[...history].sort((a,b)=>b.revision-a.revision)[0],[values,setValues]=useState(()=>Object.fromEntries(Object.keys(amountFields).map(k=>[k,((latest?.[k]||0)/100).toFixed(2)]))),[note,setNote]=useState('');
 if(reservation.kind==='block')return null;const matched=financialMatches(latest,reservation);let totals;try{totals=validateAmounts(Object.fromEntries(Object.entries(values).map(([k,v])=>[k,centsInput(v)])));}catch{}
 const confirmed=reservation.status==='confirmed';
 async function save(e){e.preventDefault();try{const amounts=Object.fromEntries(Object.entries(values).map(([k,v])=>[k,centsInput(v)]));validateAmounts(amounts);setError('');await onAction(async()=>{const {error}=await db.rpc('ts_save_booking_financials',{p_booking:reservation.id,p_expected:latest?.revision||0,p_property:reservation.property_id,p_arrival:reservation.arrival,p_departure:reservation.departure,p_guests:reservation.guests,p_amounts:amounts,p_note:note});if(error)throw Error(error.message);});}catch(e){setError(e.message);}}
 function draft(){try{const q=quote(property,reservation.arrival,reservation.departure,rates);setValues(v=>({...v,accommodation_cents:q.markedUp.toFixed(2)}));setError('');}catch(e){setError(e.message);}}
 return <><button className="link" disabled={busy} onClick={()=>setOpen(!open)}>{open?'Close amounts':latest?'Booking amounts':'Add booking amounts'}</button>{open&&<div className="reservation-editor booking-amounts"><h3>Saved booking charges</h3><p>USD · whole-stay amounts. These records track agreed charges; they do not charge the guest or record collected payments.</p>{latest&&<p>Revision {latest.revision} · {money(Number(latest.total_cents)/100)} total including taxes · {matched?'Matches this booking':'Needs review: booking details changed'}</p>}{confirmed&&<form onSubmit={save}><button className="small" type="button" disabled={busy} onClick={draft}>Draft accommodation from current rates</button><p>Check the agreed booking amount before saving this draft. Fees and taxes are entered separately.</p>{Object.entries(amountFields).map(([key,label])=><label key={key}>{label} ($)<input required type="number" min="0" max="10000000" step="0.01" value={values[key]} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))}/></label>)}{totals&&<p><strong>Guest charge total {money(totals.total/100)}</strong><br/>Accommodation after discount {money(totals.net/100)} · guest fees {money(totals.fees/100)} · taxes {money(centsInput(values.tax_cents)/100)}. Host channel fees are recorded separately.</p>}<label>Reason / reference for this revision<textarea maxLength="1000" value={note} onChange={e=>setNote(e.target.value)} required placeholder="Agreed booking total, correction or amended stay"/></label><label className="financial-confirm"><input type="checkbox" required/>I checked these amounts against the agreed booking charges.</label><button disabled={busy}>Save charge revision</button>{error&&<p role="alert">{error}</p>}</form>}{!confirmed&&<p>This booking is cancelled. Saved revisions remain available for review and are excluded from booked-charge reports. Refund reconciliation is pending.</p>}{history.length>0&&<details><summary>Charge history ({history.length})</summary>{[...history].sort((a,b)=>b.revision-a.revision).map(h=><article key={h.id}><strong>Revision {h.revision} · {money(Number(h.total_cents)/100)}</strong><p>{h.arrival} → {h.departure} · {h.guests} guests · {new Date(h.created_at).toLocaleString()}</p><p>{Object.entries(amountFields).map(([k,label])=>`${label}: ${money(Number(h[k])/100)}`).join(' · ')}</p><p>{h.note}</p></article>)}</details>}</div>}</>;
}
