import {GuestBookingFields} from './guest-profiles.jsx';
import {normalizeGuestPhone} from './guest-profiles.mjs';
import React,{useState} from 'react';
import {insert,cancel,updateRecord} from './backend';
function Input({label,...props}){return <label>{label}<input required {...props}/></label>}
export function CalendarBlocks({properties,reservations,user,busy,onAction}){
 const blocks=reservations.filter(r=>r.kind==='block');
 return <section className="panel"><h2>Blocked dates</h2><p>Reserve nights for maintenance, owner stays or other unavailable periods. The end date is available for the next arrival. Blocks stay in Treestand until channel publishing is connected.</p><form className="form-grid" onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));onAction(()=>insert('reservations',{owner_id:user.id,property_id:f.property_id,guest:f.reason,arrival:f.arrival,departure:f.departure,guests:1,kind:'block',status:'blocked',note:f.note}));}}><label>Listing<select required name="property_id"><option value="">Choose a listing</option>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><Input label="Reason" name="reason" maxLength="100" placeholder="Maintenance or owner stay"/><Input label="Start date" name="arrival" type="date"/><Input label="End date (available again)" name="departure" type="date"/><label>Note<textarea name="note" maxLength="2000" rows="2"/></label><button disabled={busy||!properties.length}>Block dates</button></form>{blocks.map(r=><div className="listing" key={r.id}><div><strong>{r.guest}</strong><p>{properties.find(p=>p.id===r.property_id)?.name} Â· {r.arrival} â€” {r.departure} Â· {r.status==='cancelled'?'Released':'Blocked'}</p>{r.note&&<p>{r.note}</p>}{r.status==='blocked'&&<button className="link" disabled={busy} onClick={()=>onAction(()=>cancel(r.id))}>Release dates</button>}</div></div>)}</section>;
}
export function ReservationEditor({reservation,properties,profiles=[],busy,onAction}){
 const [open,setOpen]=useState(false);
 if(reservation.status!=='confirmed')return null;
 return <><button className="link" disabled={busy} onClick={()=>setOpen(!open)}>{open?'Close editor':'Edit booking'}</button>{open&&<form className="reservation-editor" onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));onAction(()=>updateRecord('reservations',reservation.id,{property_id:f.property_id,guest:f.guest,guest_id:f.guest_id||null,guest_phone:normalizeGuestPhone(f.guest_phone),arrival:f.arrival,departure:f.departure,guests:Number(f.guests),note:f.note}));}}><label>Listing<select required name="property_id" defaultValue={reservation.property_id}>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><GuestBookingFields profiles={profiles} initialGuestId={reservation.guest_id||reservation.id} initialName={reservation.guest} initialPhone={reservation.guest_phone||''}/><Input label="Arrival" name="arrival" type="date" defaultValue={reservation.arrival}/><Input label="Departure" name="departure" type="date" defaultValue={reservation.departure}/><Input label="Guests" name="guests" type="number" min="1" max="100" defaultValue={reservation.guests}/><label>Note<textarea name="note" maxLength="2000" defaultValue={reservation.note} rows="2"/></label><button disabled={busy}>Save booking changes</button></form>}</>;
}
export function ListingEditor({property,busy,onAction}){
 const [error,setError]=useState('');
 return <details><summary>Edit listing settings</summary><form className="form-grid" onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{new Intl.DateTimeFormat('en',{timeZone:f.timezone});setError('');onAction(()=>updateRecord('properties',property.id,{name:f.name,timezone:f.timezone,max_guests:Number(f.max_guests),min_stay:Number(f.min_stay),check_in:f.check_in,check_out:f.check_out}));}catch{setError('Enter a valid timezone.');}}}><Input label="Listing name" name="name" maxLength="120" defaultValue={property.name}/><Input label="Timezone" name="timezone" defaultValue={property.timezone}/><Input label="Maximum guests" name="max_guests" type="number" min="1" max="100" defaultValue={property.max_guests}/><Input label="Minimum nights" name="min_stay" type="number" min="1" max="365" defaultValue={property.min_stay}/><Input label="Check-in" name="check_in" type="time" defaultValue={property.check_in.slice(0,5)}/><Input label="Check-out" name="check_out" type="time" defaultValue={property.check_out.slice(0,5)}/><button disabled={busy}>Save listing settings</button>{error&&<p role="alert">{error}</p>}</form><p>New limits apply when creating or editing bookings. Existing bookings are retained. Changes to check-in, checkout or timezone also affect welcome-display timing.</p></details>;
}
