import React,{useEffect,useState} from 'react';
import {db} from './backend';
import {displayImageBucket,imageExtension,nextImagePosition} from './display-media.mjs';
export function DisplayImages({property,user,onLoaded}){
 const [images,setImages]=useState([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[videoStatus,setVideoStatus]=useState('');
 async function load(){const {data,error}=await db.from('ts_display_images').select('id,object_path,caption,position').eq('property_id',property.id).eq('owner_id',user.id).order('position');if(error)throw error;
 const signed=data.length?await db.storage.from(displayImageBucket).createSignedUrls(data.map(i=>i.object_path),3600):{data:[]};if(signed.error)throw signed.error;const collection=data.map((image,index)=>({...image,url:signed.data[index]?.signedUrl}));setImages(collection);onLoaded?.(collection);return data;}
 useEffect(()=>{let active=true;load().catch(e=>{if(active)setNotice(e.message);});return()=>{active=false;};},[property.id]);
 useEffect(()=>{let active=true;async function status(){const {data,error}=await db.from('ts_display_videos').select('state,last_error').eq('property_id',property.id).eq('owner_id',user.id).maybeSingle();if(active&&!error)setVideoStatus(data?.state==='ready'?'Photo video is ready. Connected LG TVs update within one minute.':data?.state==='failed'?'Photo video needs another attempt. Your previous video stays available.':data?'Preparing your photo video. This can take a few minutes.':'');}status();const timer=setInterval(status,30000);return()=>{active=false;clearInterval(timer);};},[property.id,busy]);
 async function upload(e){const files=Array.from(e.target.files||[]);e.target.value='';if(!files.length)return;setBusy(true);setNotice('Uploading photos…');let uploaded=0;try{let current=await load();for(const file of files){const ext=imageExtension(file),position=nextImagePosition(current),path=`${property.id}/${crypto.randomUUID()}.${ext}`;
 const {error:uploadError}=await db.storage.from(displayImageBucket).upload(path,file,{contentType:file.type,upsert:false,cacheControl:'120'});if(uploadError)throw uploadError;
 const {data,error}=await db.from('ts_display_images').insert({owner_id:user.id,property_id:property.id,object_path:path,position,caption:''}).select('id,position');if(error){await db.storage.from(displayImageBucket).remove([path]);throw error;}current.push(data[0]);uploaded++;}await load();setNotice(`${uploaded} photo${uploaded===1?'':'s'} uploaded. The photo video is being prepared automatically.`);
 }catch(error){await load().catch(()=>{});setNotice(`${uploaded?`${uploaded} photos uploaded. `:''}${error.message}`);}finally{setBusy(false);}}
 async function remove(image){setBusy(true);try{const {data,error}=await db.from('ts_display_images').delete().eq('id',image.id).eq('owner_id',user.id).select('id');if(error)throw error;if(!data.length)throw Error('Photo unavailable. Refresh and try again.');const removed=await db.storage.from(displayImageBucket).remove([image.object_path]);if(removed.error)throw Error('Photo removed from the slideshow; stored file cleanup failed.');await load();setNotice('Photo removed. The photo video is being prepared automatically.');}catch(e){setNotice(e.message);await load().catch(()=>{});}finally{setBusy(false);}}
 async function caption(image,value){setBusy(true);try{const {data,error}=await db.from('ts_display_images').update({caption:value.trim()}).eq('id',image.id).eq('owner_id',user.id).select('id');if(error)throw error;if(!data.length)throw Error('Photo unavailable.');await load();setNotice('Photo caption saved.');}catch(e){setNotice(e.message);}finally{setBusy(false);}}
 return <section className="panel display-image-editor"><div className="photo-heading"><div><h2>TV photo collection</h2><p>Make guests feel at home with property photos or relaxing landscapes. Uploaded photos replace the woodland starter collection.</p></div><span className="badge">{images.length} / 12 photos</span></div><label className="photo-upload">Upload TV photos<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy||images.length>=12} onChange={upload}/></label><p>JPG, PNG or WebP · up to 8 MB each · landscape images look best. Photos appear in upload order. LG TVs receive a looping video, prepared automatically in a few minutes.</p>{notice&&<p role="status">{notice}</p>}{videoStatus&&<p role="status">{videoStatus}</p>}<div className="photo-grid">{images.map(image=><article key={image.id}>{image.url&&<img src={image.url} alt={image.caption||'TV slideshow photo'}/>}<label>Photo caption<input maxLength="160" defaultValue={image.caption} key={image.id+image.caption} disabled={busy} onBlur={e=>{if(e.target.value.trim()!==image.caption)caption(image,e.target.value);}} placeholder="Optional caption"/></label><button className="link" disabled={busy} onClick={()=>remove(image)}>Remove photo</button></article>)}</div></section>;
}

