import React,{useState} from 'react';
import {Star,Users} from 'lucide-react';
import {updateRecord} from './backend';
import {normalizeGuestPhone,profileBookings} from './guest-profiles.mjs';
export function GuestBookingFields({profiles=[],initialGuestId='',initialName='',initialPhone=''}){
 const initial=profiles.find(g=>g.id===initialGuestId);
 const [selected,setSelected]=useState(initial?.id||''),[name,setName]=useState(initialName||initial?.name||''),[phone,setPhone]=useState(initialPhone||initial?.phone||'');
 const guest=profiles.find(g=>g.id===selected);
 return <><label>Saved guest<select name="guest_id" value={selected} onChange={e=>{const id=e.target.value,g=profiles.find(g=>g.id===id);setSelected(id);setName(g?.name||'');setPhone(g?.phone||'');}}><option value="">New guest</option>{profiles.map(g=><option key={g.id} value={g.id}>{g.name}{g.phone?' Â· '+g.phone:''}</option>)}</select></label><label>Guest name<input required name="guest" maxLength="100" value={name} onChange={e=>setName(e.target.value)}/></label><label>Guest phone number<input name="guest_phone" type="tel" maxLength="40" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="US number or +country code"/></label>{guest&&(guest.rating||guest.internal_notes)&&<div className="guest-private-summary"><strong>Host reference Â· private</strong>{guest.rating&&<p>Rating: {guest.rating}/5</p>}{guest.internal_notes&&<p>{guest.internal_notes}</p>}</div>}</>;
}
function ProfileEditor({profile,busy,onAction}){
 const [error,setError]=useState('');
 return <form className="form-grid" onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{const phone=normalizeGuestPhone(f.phone);setError('');onAction(()=>updateRecord('guests',profile.id,{name:f.name,phone,rating:f.rating?Number(f.rating):null,internal_notes:f.internal_notes}));}catch(err){setError(err.message);}}}><label>Guest name<input required name="name" maxLength="100" defaultValue={profile.name}/></label><label>Full phone number<input name="phone" type="tel" maxLength="40" defaultValue={profile.phone||''} placeholder="US number or +country code"/></label><label>Internal rating<select name="rating" defaultValue={profile.rating||''}><option value="">Not rated</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} / 5{n===1?' Â· Poor':n===5?' Â· Excellent':''}</option>)}</select></label><label className="guest-notes-field">Internal notes<textarea name="internal_notes" rows="4" maxLength="10000" defaultValue={profile.internal_notes} placeholder="Preferences or observations for future stays"/></label><button disabled={busy}>Save guest profile</button>{error&&<p role="alert">{error}</p>}</form>;
}
export function GuestProfiles({data,user,busy,onAction}){
 const [search,setSearch]=useState('');const needle=search.trim().toLowerCase();
 const profiles=(data.guestProfiles||[]).filter(g=>g.owner_id===user.id&&(!needle||g.name.toLowerCase().includes(needle)||(g.phone||'').includes(needle))).sort((a,b)=>a.name.localeCompare(b.name));
 return <section className="panel"><span className="eyebrow">YOUR GUESTS</span><h2>Guest profiles</h2><p>Save contact details, ratings and notes for future stays. Ratings and notes are private to your host account and are never shown on the guest TV.</p><label>Find a guest<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or phone number"/></label>{!profiles.length&&<p>No guests found. Saving a booking creates a guest profile.</p>}<div className="guest-profile-list">{profiles.map(g=>{const bookings=profileBookings(data,g,user.id);return <article className="guest-profile-card" key={g.id}><header><Users size={22} aria-hidden="true"/><div><h3>{g.name}</h3><p>{g.phone||'Full phone number not saved'}</p></div>{g.rating&&<span className="badge"><Star size={14} aria-hidden="true"/> {g.rating}/5 Â· Host rating</span>}</header>{g.internal_notes&&<p className="guest-profile-notes">{g.internal_notes}</p>}<details><summary>Edit private profile</summary><ProfileEditor key={g.id+g.updated_at} profile={g} busy={busy} onAction={onAction}/></details><details><summary>Booking history Â· {bookings.length}</summary>{bookings.map(b=><p key={b.id}>{data.properties.find(p=>p.id===b.property_id)?.name||'Listing'} Â· {b.arrival} â€” {b.departure} Â· {b.status}</p>)}</details></article>;})}</div></section>;
}
