import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {CalendarDays,House,KeyRound,MessageSquare,Settings,LogOut,CreditCard,ClipboardList} from 'lucide-react';
import {db,configured,workspace,insert,cancel} from './backend';
import {quote,money} from './model.mjs';
import './style.css';
import {Calendar} from './calendar';
import {StayWorkflow} from './stay-workflow.jsx';
import {Messages} from './messages.jsx';
import {OperationsReminders} from './operations-reminders.jsx';
import {Operations} from './operations.jsx';
import {PropertySetup} from './property-setup.jsx';
import {Pricing} from './pricing.jsx';
import {Payments} from './payments.jsx';
import {PricingDemo} from './pricing-demo.jsx';
import {GuestExperience} from './guest-experience';
import {TvDemo} from './tv-demo';
import {TvPlayer} from './tv-player';
import {phoneLastFour} from './phone-code.mjs';
import {DoorLocks} from './door-locks';
import {nativeLockCallback} from './native-lock-browser.mjs';
import {MfaGate} from './mfa.jsx';
import {requiresHostMfa} from './mfa.mjs';
import {CalendarBlocks,ReservationEditor,ListingEditor} from './calendar-controls';
const appHref=import.meta.env.BASE_URL+'app/';
function Brand(){return <a className="brand" href={import.meta.env.BASE_URL} aria-label="Treestand Manager home"><img className="brand-logo" src={`${import.meta.env.BASE_URL}brand/treestand-logo.webp`} alt="Treestand Manager" width="1200" height="400"/></a>}
function Landing(){return <><header className="public-header"><Brand/><a className="button small" href={appHref}>Host sign-in</a></header><main className="landing"><div className="eyebrow">A CERBTEK LLC PRODUCT · PILOT IN DEVELOPMENT</div><h1>A clearer view<br/>of every stay.</h1><p className="intro">Bookings, pricing and guest preparation in one place. Built for independent short-term rental hosts who want more control over their daily operations.</p><div className="actions"><a className="button" href={appHref}>Explore the host workspace</a><a href="#progress">See what’s being built</a></div><section className="public-grid" aria-label="Platform capabilities"><article><CalendarDays/><h2>Plan your calendar</h2><p>Manage manual reservations and listing rates in a dedicated host workspace.</p></article><article><MessageSquare/><h2>Prepare each arrival</h2><p>Keep guest-message drafts and room-access plans alongside your listings.</p></article><article><KeyRound/><h2>Connect your tools</h2><p>Airbnb, WelcomeScreen and TTLock connections are planned and awaiting setup and validation.</p></article></section><section id="progress" className="progress"><div><span className="eyebrow">WHERE WE ARE</span><h2>Starting small.<br/>Building for real stays.</h2></div><div><p>The initial pilot is designed around two Airbnb listings. Direct Airbnb API access is being evaluated. A Hospitable partner application is also pending as an optional connection route.</p><p>Treestand Manager is not yet accepting paid customers. Subscription pricing and public onboarding will follow validation.</p></div></section></main><footer>© {new Date().getFullYear()} CerbTek LLC · Treestand Manager</footer></>}
function Auth(){const [mode,setMode]=useState('signin'),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);setNotice('');const f=new FormData(e.currentTarget);try{const credentials={email:String(f.get('email')),password:String(f.get('password'))};const {error}=mode==='signin'?await db.auth.signInWithPassword(credentials):await db.auth.signUp({...credentials,options:{emailRedirectTo:location.origin+appHref}});if(error)throw error;if(mode==='signup')setNotice('Check your email to confirm your account before signing in.');}catch(err){setNotice(err.message);}finally{setBusy(false);}}return <main className="auth"><Brand/><h1>Your host workspace</h1>{!configured?<div className="notice">Host sign-in is not available yet. This deployment still needs its dedicated Supabase connection.</div>:<><form onSubmit={submit}><Field name="email" label="Email" type="email" autoComplete="username"/><Field name="password" label="Password" type="password" minLength="8" autoComplete={mode==='signup'?'new-password':'current-password'}/><button disabled={busy}>{busy?'Working…':mode==='signin'?'Sign in':'Create account'}</button></form><button className="link" onClick={()=>{setMode(mode==='signin'?'signup':'signin');setNotice('');}}>{mode==='signin'?'Create a host account':'Back to sign-in'}</button></>}{notice&&<p role="status">{notice}</p>}<p><a href={import.meta.env.BASE_URL}>Back to Treestand</a></p></main>}
function Field({label,...props}){return <label>{label}<input required={props.required??true} {...props}/></label>}
function Dashboard({user}){const [data,setData]=useState({properties:[],reservations:[],rates:[],templates:[],displays:[],locks:[],lockAssignments:[]}),[tab,setTab]=useState(nativeLockCallback?'locks':new URLSearchParams(location.search).has('payments')?'payments':'overview'),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[focus,setFocus]=useState(null),[cancelId,setCancelId]=useState('');async function load(){setLoading(true);try{setData(await workspace());}catch(e){setNotice(e.message);}finally{setLoading(false);}}useEffect(()=>{load();},[user.id]);async function act(job){setBusy(true);setNotice('');try{await job();await load();setNotice('Saved.');}catch(e){setNotice(e.message);}finally{setBusy(false);}}function navigate(next,propertyId,bookingId){setFocus({propertyId,bookingId});setTab(next);window.scrollTo({top:0,behavior:'smooth'});}const upcoming=data.reservations.filter(r=>r.status==='confirmed');function values(e){e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget));}function reservation(e){const v=values(e);const p=data.properties.find(p=>p.id===v.property_id);try{const n=quote(p,v.arrival,v.departure,data.rates).nights;if(n<p.min_stay)throw Error(`Minimum stay is ${p.min_stay} nights.`);if(Number(v.guests)>p.max_guests)throw Error(`Maximum occupancy is ${p.max_guests}.`);const {guest_phone,...bookingValues}=v;const guest_phone_last4=phoneLastFour(guest_phone);act(()=>insert('reservations',{...bookingValues,guest_phone_last4,guests:Number(v.guests),owner_id:user.id}));}catch(err){setNotice(err.message);}}return <div className="shell"><aside><Brand/><nav>{[['overview',House,'Overview'],['properties',House,'Properties'],['bookings',CalendarDays,'Bookings'],['operations',ClipboardList,'Operations'],['pricing',Settings,'Pricing'],['payments',CreditCard,'Payments'],['messages',MessageSquare,'Messages'],['guest',House,'Guest Experience'],['locks',KeyRound,'Door locks'],['connections',KeyRound,'Connections']].map(([id,Icon,label])=><button key={id} className={tab===id?'selected':''} onClick={()=>{setFocus(null);setTab(id);}}><Icon size={19}/>{label}</button>)}</nav><button className="signout" onClick={()=>db.auth.signOut()}><LogOut size={16}/>Sign out</button></aside><main className="workspace"><div className="topline"><span>HOST WORKSPACE</span><span>{user.email}</span></div><h1>{tab==='locks'?'Door locks':tab==='guest'?'Guest Experience':tab[0].toUpperCase()+tab.slice(1)}</h1><div className="notice">Manual workspace · live bookings, price publishing, messages and door-code automation are not connected.</div>{notice&&<p className="feedback" role="status">{notice}</p>}{loading?<p role="status">Loading your workspace…</p>:<>
{tab==='overview'&&<><OperationsReminders data={data} user={user} onNavigate={navigate}/><PropertySetup data={data} user={user} busy={busy} onAction={act} onNavigate={navigate} onRefresh={load} compact/><StayWorkflow data={data} user={user} onNavigate={navigate} onRefresh={load} busy={busy||loading} compact/><div className="stats"><article><span>Listings</span><strong>{data.properties.length}</strong></article><article><span>Confirmed reservations</span><strong>{upcoming.length}</strong></article><article><span>Saved TV registrations</span><strong>{data.displayDevices?.filter(d=>!d.revoked&&!d.pairing_expires_at&&Date.parse(d.expires_at)>Date.now()).length||0}</strong></article></div><section className="panel"><h2>Your listings</h2>{data.properties.map(p=><div className="listing" key={p.id}><House/><div><strong>{p.name}</strong><p>{p.timezone} · Check-in {p.check_in.slice(0,5)} · Check-out {p.check_out.slice(0,5)}</p><p>{money(p.weekday_cents/100)} weekdays / {money(p.weekend_cents/100)} Friday–Saturday · {p.max_guests} guests</p><ListingEditor key={p.id+JSON.stringify(p)} property={p} busy={busy} onAction={act}/></div></div>)}{!data.properties.length&&<p>Add your first listing to begin. Each account starts with an empty workspace.</p>}<details><summary>Add a listing</summary><form className="form-grid" onSubmit={e=>{const v=values(e);try{new Intl.DateTimeFormat('en',{timeZone:v.timezone});}catch{setNotice('Enter a valid timezone.');return;}act(()=>insert('properties',{name:v.name,timezone:v.timezone,owner_id:user.id,weekday_cents:Math.round(Number(v.weekday)*100),weekend_cents:Math.round(Number(v.weekend)*100),markup_percent:Number(v.markup),max_guests:Number(v.max_guests),min_stay:Number(v.min_stay),check_in:v.check_in,check_out:v.check_out}));}}><Field label="Listing name" name="name" maxLength="120"/><Field label="Timezone" name="timezone" defaultValue="America/New_York"/><Field label="Weekday rate ($)" name="weekday" type="number" min="1" max="10000" step="0.01" defaultValue="56"/><Field label="Friday/Saturday rate ($)" name="weekend" type="number" min="1" max="10000" step="0.01" defaultValue="70"/><Field label="Channel markup (%)" name="markup" type="number" min="0" max="100" step="0.01" defaultValue="18.34"/><Field label="Maximum guests" name="max_guests" type="number" min="1" max="100" defaultValue="2"/><Field label="Minimum nights" name="min_stay" type="number" min="1" max="365" defaultValue="1"/><Field label="Check-in" name="check_in" type="time" defaultValue="15:00"/><Field label="Check-out" name="check_out" type="time" defaultValue="11:00"/><button disabled={busy}>Add listing</button></form></details></section></>}
{tab==='properties'&&<PropertySetup key={focus?.propertyId||'setup'} initialPropertyId={focus?.propertyId} data={data} user={user} busy={busy} onAction={act} onNavigate={navigate} onRefresh={load}/>}
{tab==='bookings'&&<><StayWorkflow data={data} user={user} onNavigate={navigate} onRefresh={load} busy={busy||loading}/><Calendar properties={data.properties} reservations={data.reservations}/><CalendarBlocks properties={data.properties} reservations={data.reservations} user={user} busy={busy} onAction={act}/><section className="panel"><h2>Reservations</h2>{!data.reservations.filter(r=>r.kind!=='block').length&&<p>No reservations yet. Add confirmed bookings manually while channel connections are pending.</p>}<div className="table-wrap"><table><thead><tr><th>Guest</th><th>Listing</th><th>Stay</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.reservations.filter(r=>r.kind!=='block').map(r=><tr key={r.id}><td>{r.guest}</td><td>{data.properties.find(p=>p.id===r.property_id)?.name}</td><td>{r.arrival} — {r.departure}</td><td>{r.status}</td><td><ReservationEditor key={r.id+JSON.stringify(r)} reservation={r} properties={data.properties} busy={busy} onAction={act}/>{r.status==='confirmed'&&(cancelId===r.id?<div className="cancel-review"><p>Cancel {r.guest}’s stay? Dates become available, the personalized TV greeting stops, and door-access cleanup is queued. Lock removal still needs provider verification.</p><button className="small" disabled={busy} onClick={()=>act(async()=>{await cancel(r.id);setCancelId('');})}>Confirm cancellation</button><button className="link" disabled={busy} onClick={()=>setCancelId('')}>Keep booking</button></div>:<button className="link" disabled={busy} onClick={()=>setCancelId(r.id)}>Cancel booking</button>)}</td></tr>)}</tbody></table></div></section><section className="panel"><h2>Add a reservation</h2><form className="form-grid" onSubmit={reservation}><PropertySelect key={focus?.propertyId||'booking-listing'} initialPropertyId={focus?.propertyId} properties={data.properties}/><Field label="Guest name" name="guest" maxLength="100"/><Field required={false} label="Guest phone number (for door code)" name="guest_phone" type="tel" maxLength="40"/><Field label="Arrival" name="arrival" type="date"/><Field label="Departure" name="departure" type="date"/><Field label="Guests" name="guests" type="number" min="1" max="100" defaultValue="1"/><Field required={false} label="Note" name="note" maxLength="2000"/><button disabled={busy||!data.properties.length}>Save manual booking</button></form></section></>}
{tab==='operations'&&<Operations data={data} user={user} busy={busy} onAction={act} onRefresh={load}/>}
{tab==='pricing'&&<Pricing key={focus?.propertyId||'pricing'} initialPropertyId={focus?.propertyId} properties={data.properties} rates={data.rates} reservations={data.reservations} comparables={data.comparables||[]} user={user} busy={busy} onAction={act}/>}
{tab==='payments'&&<Payments user={user}/>}
{tab==='messages'&&<Messages data={data} user={user} busy={busy} onAction={act} onRefresh={load}/>}
{tab==='guest'&&<GuestExperience key={focus?.propertyId||'guest'} initialPropertyId={focus?.propertyId} properties={data.properties} reservations={data.reservations} displays={data.displays} user={user} onSaved={load}/>}
{tab==='locks'&&<DoorLocks initialPropertyId={focus?.propertyId} initialBookingId={focus?.bookingId} data={data} user={user} busy={busy} onAction={act}/>}
{tab==='connections'&&<><section className="panel"><h2>Connection status</h2>{[['Airbnb','Direct partner access is being evaluated. Hospitable is an optional route with an application pending. No approved connection or credentials yet.'],['WelcomeScreen','Account verification and booking-feed setup are pending.'],['TTLock','Inventory, room/shared-entrance assignments and guest access plans are available in Door locks. Developer credentials and live account connection are pending.']].map(([name,text])=><article className="listing" key={name}><KeyRound/><div><h3>{name}</h3><p>{text}</p><span className="badge">Not connected</span></div></article>)}</section><section className="panel"><h2>Access plan</h2><p>Room-specific locks plus a shared entrance will be assigned after TTLock verification. No lock credentials are stored in this frontend.</p><button onClick={()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='treestand-backup.json';a.click();URL.revokeObjectURL(url);}}>Export workspace backup</button></section></>}
</>}</main></div>}
function PropertySelect({properties,initialPropertyId}){return <label>Listing<select name="property_id" required defaultValue={initialPropertyId||''}><option value="">Choose a listing</option>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
function App(){const [session,setSession]=useState(null),[ready,setReady]=useState(!configured);useEffect(()=>{if(!db||!location.pathname.slice(import.meta.env.BASE_URL.length).startsWith('app'))return;let active=true;db.auth.getSession().then(({data})=>{if(active){setSession(data.session);setReady(true);}}).catch(()=>{if(active)setReady(true);});const {data:{subscription}}=db.auth.onAuthStateChange((event,s)=>{setSession(s);setReady(true);});return()=>{active=false;subscription.unsubscribe();};},[]);const relative=location.pathname.startsWith(import.meta.env.BASE_URL)?location.pathname.slice(import.meta.env.BASE_URL.length):location.pathname;const isApp=relative==='app'||relative.startsWith('app/');if(relative==='pricing/demo'||relative==='pricing/demo/')return <PricingDemo/>;if(relative==='display/demo'||relative==='display/demo/')return <TvDemo/>;if(relative==='display'||relative.startsWith('display/'))return <TvPlayer/>;if(!isApp)return <Landing/>;if(!ready)return <main className="auth" role="status">Loading sign-in…</main>;return session?(requiresHostMfa(session.user)?<MfaGate key={session.user.id} session={session}><Dashboard key={session.user.id} user={session.user}/></MfaGate>:<Dashboard key={session.user.id} user={session.user}/>):<Auth/>}
createRoot(document.getElementById('root')).render(<App/>);
