import React,{useState,useRef} from 'react';
import {updatePricing,editRates,saveComparable,removeComparable} from './backend';
import {quote,money,nights,validDay} from './model.mjs';
import {dayNames,stayTypes,todayInZone,addDay,nightRate,priceCalendar,pricePreview,marketAdvice} from './pricing-model.mjs';
const allDays=[0,1,2,3,4,5,6];
function Field({label,...props}){return <label>{label}<input required {...props}/></label>}
export function Pricing({properties,...props}){
 const [selected,setSelected]=useState(properties[0]?.id||'');
 const p=properties.find(p=>p.id===selected)||properties[0];
 if(!p)return <section className="panel"><h2>Your pricing workspace</h2><p>Add a listing in Overview to begin setting prices.</p></section>;
 return <><div className="pricing-heading"><div><span className="eyebrow">YOUR RATES, YOUR CONTROL</span><p>Plan each night, adjust seasons, and compare local rates.</p></div><label>Listing<select value={p.id} onChange={e=>setSelected(e.target.value)}>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><ListingPricing key={p.id} property={p} {...props}/></>;
}
function ListingPricing({property:p,rates,reservations,comparables,user,busy,onAction}){
 const today=todayInZone(p.timezone),[month,setMonth]=useState(today.slice(0,7)),[single,setSingle]=useState(true),[edit,setEdit]=useState({start:today,end:today,weekdays:allDays,mode:'set',value:p.weekday_cents,floor:100,ceiling:1000000}),[preview,setPreview]=useState(null),[error,setError]=useState(''),[estimate,setEstimate]=useState(null),[arrival,setArrival]=useState(today),[departure,setDeparture]=useState(addDay(today)),[guests,setGuests]=useState(Math.min(2,p.max_guests));
 const editor=useRef(null),grid=priceCalendar(p,month,rates,reservations),ownComps=comparables.filter(c=>c.property_id===p.id),advice=marketAdvice(p,ownComps,arrival,departure,guests,today);
 const ownRates=rates.filter(r=>r.property_id===p.id&&r.day>=today);
 function patch(value){setEdit(old=>({...old,...value}));setPreview(null);setError('');}
 function selectDay(day){setSingle(true);patch({start:day,end:day,weekdays:allDays,mode:'set',value:nightRate(p,day,rates).cents});editor.current?.scrollIntoView({block:'start'});}
 function tryPreview(e){e.preventDefault();try{setPreview(pricePreview(p,rates,edit));setError('');}catch(e){setPreview(null);setError(e.message);}}
 function useSuggestion(){setSingle(false);patch({start:arrival,end:addDay(departure,-1),weekdays:allDays,mode:'set',value:advice.baseCents});editor.current?.scrollIntoView({block:'start'});}
 return <><div className="stats pricing-stats"><article><span>Weekday base</span><strong>{money(p.weekday_cents/100)}</strong><small>Sunday–Thursday</small></article><article><span>Weekend base</span><strong>{money(p.weekend_cents/100)}</strong><small>Friday–Saturday</small></article><article><span>Upcoming date overrides</span><strong>{ownRates.length}</strong><small>Saved in Treestand</small></article></div>
 <section className="panel pricing-calendar"><div className="calendar-toolbar"><div><h2>Nightly pricing calendar</h2></div><label>Month<input type="month" required value={month} onChange={e=>{if(/^\d{4}-\d{2}$/.test(e.target.value)&&e.target.value.slice(0,4)>='0001')setMonth(e.target.value);}}/></label></div><p>Select a night to change its price. Base rates are before markup. Changes affect future estimates; existing reservations stay unchanged.</p><div className="price-legend"><span>Base rate</span><span className="price-override-key">Date override</span><span className="badge">Booked / blocked</span></div><div className="calendar-scroll"><div className="calendar-grid"><div className="calendar-week">{dayNames.map(d=><div key={d}>{d}</div>)}</div><div className="price-cells">{Array.from({length:grid.padding},(_,i)=><div aria-hidden="true" key={'pad'+i}/>)}{grid.days.map(d=><button type="button" disabled={busy} key={d.day} className={(d.override?'price-override ':'')+(d.bookings.length?'price-occupied ':'')+(edit.start<=d.day&&edit.end>=d.day&&edit.weekdays.includes(new Date(d.day+'T12:00:00Z').getUTCDay())?'price-selected':'')} aria-label={`${d.day}: ${money(d.cents/100)} base${d.override?', date override':''}${d.bookings.length?', booked or blocked':''}. Edit price`} onClick={()=>selectDay(d.day)}><span className="price-day">{Number(d.day.slice(-2))}{d.override&&<small>Override</small>}</span><strong>{money(d.cents/100)}</strong>{Number(p.markup_percent)>0&&<small>{money(d.guestCents/100)} with markup</small>}{d.bookings.length>0&&<span className="price-status">{d.bookings.some(b=>b.kind==='block')?'Blocked':'Booked'}</span>}</button>)}</div></div></div></section>
 <section className="panel" ref={editor}><div className="photo-heading"><div><h2>Set prices for your dates</h2><p>Single nights, seasonal ranges, event weekends, and last-minute adjustments.</p></div><span className="badge">Preview before saving</span></div><form onSubmit={tryPreview}><fieldset className="price-options"><legend>Dates to change</legend>{[[true,'Single date'],[false,'Date range']].map(([v,label])=><label key={label}><input type="radio" name="selection" checked={single===v} onChange={()=>{setSingle(v);patch({end:edit.start,weekdays:allDays});}}/>{label}</label>)}</fieldset><div className="form-grid"><Field label={single?'Date':'First night'} type="date" value={edit.start} onChange={e=>patch({start:e.target.value,...(single?{end:e.target.value}:{})})}/>{!single&&<Field label="Last night (included)" type="date" min={edit.start} value={edit.end} onChange={e=>patch({end:e.target.value})}/>}</div>{!single&&<fieldset className="price-options weekdays"><legend>Apply only to these days</legend>{dayNames.map((d,i)=><label key={d}><input type="checkbox" checked={edit.weekdays.includes(i)} onChange={e=>patch({weekdays:e.target.checked?[...edit.weekdays,i]:edit.weekdays.filter(n=>n!==i)})}/>{d}</label>)}<button type="button" className="link" onClick={()=>patch({weekdays:allDays})}>All days</button><button type="button" className="link" onClick={()=>patch({weekdays:[5,6]})}>Friday & Saturday</button></fieldset>}
 <div className="form-grid"><label>Price action<select value={edit.mode} onChange={e=>patch({mode:e.target.value,value:e.target.value==='percent'?10:p.weekday_cents})}><option value="set">Set a nightly price</option><option value="percent">Raise or lower current prices (%)</option><option value="clear">Restore weekday / weekend base rates</option></select></label>{edit.mode!=='clear'&&<Field label={edit.mode==='set'?'Nightly base price ($)':'Adjustment (%) · negative lowers price'} type="number" min={edit.mode==='set'?1:-99} max={edit.mode==='set'?10000:100} step="0.01" value={Number.isFinite(edit.value)?(edit.mode==='set'?edit.value/100:edit.value):''} onChange={e=>patch({value:e.target.value===''?NaN:edit.mode==='set'?Math.round(Number(e.target.value)*100):Number(e.target.value)})}/>}{edit.mode!=='clear'&&<><Field label="Minimum base price for this edit ($)" type="number" min="1" max="10000" step="0.01" value={edit.floor/100} onChange={e=>patch({floor:Math.round(Number(e.target.value)*100)})}/><Field label="Maximum base price for this edit ($)" type="number" min="1" max="10000" step="0.01" value={edit.ceiling/100} onChange={e=>patch({ceiling:Math.round(Number(e.target.value)*100)})}/></>}</div><p>Percentage changes use each night’s current base price, including existing overrides. Markup ({p.markup_percent}%) is applied afterward. Restoring base rates removes the selected overrides.</p><button disabled={busy}>Preview price changes</button></form>{error&&<p className="feedback" role="alert">{error}</p>}{preview&&<div className="price-preview"><h3>{preview.rows.length} {preview.rows.length===1?'night':'nights'} ready to {edit.mode==='clear'?'restore':'update'}</h3><p>{edit.start} through {edit.end} · {edit.weekdays.map(d=>dayNames[d]).join(', ')}</p><div className="table-wrap price-preview-table"><table><thead><tr><th>Night</th><th>Current base</th><th>New base</th><th>With markup</th></tr></thead><tbody>{preview.rows.map(r=><tr key={r.day}><td>{r.day}</td><td>{money(r.cents/100)}</td><td>{money(r.nextCents/100)}</td><td>{money(r.nextGuestCents/100)}</td></tr>)}</tbody></table></div><button disabled={busy} onClick={()=>onAction(()=>editRates(p.id,edit,preview.expected))}>{edit.mode==='clear'?'Restore base pricing':'Save these prices'}</button><p>Saved prices stay in Treestand. Channel publishing is not connected.</p></div>}</section>
 <section className="panel"><h2>Base rates & market settings</h2><details><summary>Adjust your regular rates and comparison area</summary><form className="form-grid" onSubmit={e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));onAction(()=>updatePricing(p.id,{weekday_cents:Math.round(Number(v.weekday)*100),weekend_cents:Math.round(Number(v.weekend)*100),markup_percent:Number(v.markup),market:v.market.trim(),accommodation_type:v.accommodation_type}));}}><Field label="Weekday base price ($)" name="weekday" type="number" min="1" max="10000" step="0.01" defaultValue={p.weekday_cents/100}/><Field label="Friday / Saturday base price ($)" name="weekend" type="number" min="1" max="10000" step="0.01" defaultValue={p.weekend_cents/100}/><Field label="Markup (%)" name="markup" type="number" min="0" max="100" step="0.01" defaultValue={p.markup_percent}/><Field label="Comparison market / neighborhood" name="market" maxLength="160" defaultValue={p.market} placeholder="e.g. Garner, NC"/><label>Accommodation type<select name="accommodation_type" defaultValue={p.accommodation_type}>{Object.entries(stayTypes).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><button disabled={busy}>Save base & market settings</button></form><p>Date overrides keep their saved base price until you change or restore them. Markup changes also apply to overrides.</p></details></section>
 <section className="panel"><div className="photo-heading"><div><h2>Compare rates in your area</h2><p>{p.market||'Choose a comparison market above'} · {stayTypes[p.accommodation_type]}</p></div><span className="badge">Host-entered comparisons</span></div><p>Compare similar listings for the same stay. Enter the accommodation-only nightly price before taxes and fees. If a source shows a stay total, subtract fees and taxes, then divide by the number of nights. These are observed asking prices, not proven booking rates or a guarantee of the best price. Live market data is not connected yet.</p><div className="form-grid"><Field label="Compare arrival" type="date" value={arrival} onChange={e=>setArrival(e.target.value)}/><Field label="Compare departure" type="date" min={addDay(validDateOrToday(arrival,today))} value={departure} onChange={e=>setDeparture(e.target.value)}/><Field label="Guests for comparison" type="number" min="1" max="100" value={guests} onChange={e=>setGuests(Number(e.target.value))}/></div><div className="market-advice">{advice.median?<><span className="eyebrow">MEDIAN OF {advice.eligible.length} MATCHING SOURCES</span><strong>{money(advice.median/100)} <small>/ night before fees & taxes</small></strong><p>Observed range {money(advice.low/100)}–{money(advice.high/100)}. With your {p.markup_percent}% markup, the suggested base rate is {money(advice.baseCents/100)}.</p><button disabled={busy||Boolean(advice.reason)} onClick={useSuggestion}>Use suggestion in date editor</button><p>You’ll preview the exact dates and prices before saving.</p></>:<p>{advice.reason}</p>}{advice.median&&advice.reason&&<p role="alert">{advice.reason}</p>}</div>
 <details><summary>Add or refresh a comparable rate</summary><form className="form-grid" onSubmit={e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));try{const url=new URL(v.source_url);if(url.protocol!=='https:'||url.username||url.password)throw Error('Use a public HTTPS listing URL.');for(const key of [...url.searchParams.keys()])if(key.startsWith('utm_')||['fbclid','gclid'].includes(key))url.searchParams.delete(key);url.hash='';onAction(()=>saveComparable({owner_id:user.id,property_id:p.id,name:v.name.trim(),market:v.market.trim(),accommodation_type:v.accommodation_type,source_url:url.href.replace(/\/$/,''),arrival,departure,guests,nightly_cents:Math.round(Number(v.nightly)*100),observed_on:v.observed_on}));setError('');}catch(e){setError(e.message);}}}><Field label="Comparable listing name" name="name" maxLength="120"/><Field label="Public listing source URL" name="source_url" type="url" maxLength="2000" placeholder="https://…"/><Field label="Market / neighborhood" name="market" maxLength="160" defaultValue={p.market}/><label>Accommodation type<select required name="accommodation_type" defaultValue={p.accommodation_type==='unspecified'?'private_room':p.accommodation_type}>{Object.entries(stayTypes).filter(([k])=>k!=='unspecified').map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><Field label="Accommodation nightly price ($)" name="nightly" type="number" min="1" max="10000" step="0.01"/><Field label="Date you checked this rate" name="observed_on" type="date" max={today} defaultValue={today}/><p>For {arrival} → {departure}, {guests} guests. Saving the same source for this stay refreshes its observation.</p><button disabled={busy||!arrival||!departure||departure<=arrival||guests<1}>Save comparable rate</button></form></details>
 {ownComps.length>0&&<div className="table-wrap"><table><thead><tr><th>Comparable</th><th>Stay / guests</th><th>Nightly rate</th><th>Checked</th><th>Comparison</th><th/></tr></thead><tbody>{ownComps.map(c=><tr key={c.id}><td><a href={/^https:\/\//.test(c.source_url)?c.source_url:undefined} target="_blank" rel="noreferrer">{c.name}</a><small className="comparable-meta">{c.market} · {stayTypes[c.accommodation_type]}</small></td><td>{c.arrival} → {c.departure}<small className="comparable-meta">{c.guests} guests</small></td><td>{money(c.nightly_cents/100)}</td><td>{c.observed_on}</td><td>{advice.eligible.some(e=>e.id===c.id)?'Matching':'Excluded: stay, market, type, guests or age'}</td><td><button className="link" disabled={busy} onClick={()=>onAction(()=>removeComparable(c.id))}>Remove</button></td></tr>)}</tbody></table></div>}</section>
 <section className="panel"><h2>Stay estimate</h2><form className="form-grid" onSubmit={e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));try{const q=quote(p,v.arrival,v.departure,rates),rows=Array.from({length:nights(v.arrival,v.departure)},(_,i)=>nightRate(p,addDay(v.arrival,i),rates));setEstimate({...q,rows});setError('');}catch(e){setError(e.message);}}}><Field label="Arrival" name="arrival" type="date"/><Field label="Departure" name="departure" type="date"/><button disabled={busy}>Calculate stay</button></form>{estimate&&<><p><strong>{estimate.nights} nights · {money(estimate.markedUp)} with markup</strong><br/>Base {money(estimate.total)} + markup {money(estimate.markedUp-estimate.total)}. Accommodation estimate only; fees and taxes excluded.</p><div className="table-wrap price-preview-table"><table><thead><tr><th>Night</th><th>Source</th><th>Base price</th></tr></thead><tbody>{estimate.rows.map(r=><tr key={r.day}><td>{r.day}</td><td>{r.override?'Date override':'Regular base rate'}</td><td>{money(r.cents/100)}</td></tr>)}</tbody></table></div></>}{error&&<p role="alert">{error}</p>}</section></>;
}
function validDateOrToday(value,today){return validDay(value)?value:today;}
