import React,{useState,useEffect} from 'react';import {db} from './backend.js';import {money} from './model.mjs';import {todayInZone,addDay} from './pricing-model.mjs';import {centsInput} from './booking-financials.mjs';import {rulesFor,percentageBps,validateRules,ruleQuote} from './pricing-rules.mjs';
export function PricingRules({property,rows=[],busy,onAction}){const rules=rulesFor(rows,property.id);return <RuleSettings key={property.id+':'+rules.revision} property={property} rules={rules} busy={busy} onAction={onAction}/>;}
function RuleSettings({property,rules,busy,onAction}){
 const [error,setError]=useState('');async function submit(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{const values=validateRules({cleaning_cents:centsInput(f.cleaning),included_guests:Number(f.included),extra_guest_cents:centsInput(f.extra),weekly_bps:percentageBps(f.weekly),monthly_bps:percentageBps(f.monthly),last_minute_days:Number(f.days),last_minute_bps:percentageBps(f.last)});setError('');await onAction(async()=>{const {error}=await db.rpc('ts_save_pricing_rules',{p_property:property.id,p_expected:rules.revision,p_values:values});if(error)throw Error(error.message);});}catch(e){setError(e.message);}}
 return <section className="panel"><h2>Fees and automatic quote discounts</h2><p>Save rules for future estimates and booking charge drafts. Existing booking amounts retain their saved revisions. Channel publishing and automatic tax calculation remain pending.</p><form className="form-grid" onSubmit={submit}><Field label="Cleaning fee per stay ($)" name="cleaning" max="10000" value={rules.cleaning_cents/100}/><Field label="Guests included in the base price" name="included" type="number" min="1" max="100" step="1" value={rules.included_guests}/><Field label="Extra guest fee per person, per night ($)" name="extra" max="1000" value={rules.extra_guest_cents/100}/><Field label="Weekly discount · 7+ nights (%)" name="weekly" max="100" value={rules.weekly_bps/100}/><Field label="Monthly discount · 28+ nights (%)" name="monthly" max="100" value={rules.monthly_bps/100}/><Field label="Last-minute window · days before arrival (0 disables)" name="days" type="number" max="365" step="1" value={rules.last_minute_days}/><Field label="Last-minute accommodation discount (%)" name="last" max="100" value={rules.last_minute_bps/100}/><button disabled={busy}>Save fee and discount rules</button></form><p>Discounts apply to accommodation after markup. The largest eligible discount wins; discounts do not stack. On a tie: monthly, weekly, then last-minute. Cleaning is charged once; extra guest fees apply to every occupied night. Fees are not discounted.</p>{error&&<p role="alert">{error}</p>}</section>;
}
function Field({label,value,type='number',min='0',step='0.01',...props}){return <label>{label}<input required type={type} min={min} step={step} defaultValue={value} {...props}/></label>;}
export function RuleEstimate({property,rates,rows=[]}){
 const today=todayInZone(property.timezone),[form,setForm]=useState({arrival:today,departure:addDay(today),guests:1,quotedOn:today}),[preview,setPreview]=useState(null),[error,setError]=useState(''),rules=rulesFor(rows,property.id);
 useEffect(()=>{setPreview(null);},[property,rates,rows]);function patch(v){setForm(f=>({...f,...v}));setPreview(null);setError('');}
 return <section className="panel"><h2>Itemized stay estimate</h2><p>Calculate a draft using saved date overrides, markup, fees and discounts. Use the actual booking date when reviewing an existing stay. Taxes, other fees and host channel fees are entered separately in booking amounts.</p><form className="form-grid" onSubmit={e=>{e.preventDefault();try{setPreview(ruleQuote(property,form.arrival,form.departure,Number(form.guests),rates,rules,form.quotedOn));setError('');}catch(e){setPreview(null);setError(e.message);}}}><label>Estimate arrival<input required type="date" value={form.arrival} onChange={e=>patch({arrival:e.target.value})}/></label><label>Estimate departure<input required type="date" min={addDay(form.arrival||today)} value={form.departure} onChange={e=>patch({departure:e.target.value})}/></label><label>Guests for estimate<input required type="number" min="1" max={property.max_guests} value={form.guests} onChange={e=>patch({guests:e.target.value})}/></label><label>Booking / quote date<input required type="date" max={form.arrival} value={form.quotedOn} onChange={e=>patch({quotedOn:e.target.value})}/></label><button>Preview itemized estimate</button></form>{error&&<p role="alert">{error}</p>}{preview&&<QuoteBreakdown preview={preview}/>}</section>;
}
export function QuoteBreakdown({preview:q}){return <div className="price-preview"><h3>{q.nights} nights · {money(q.total/100)} before taxes and other charges</h3><dl className="quote-breakdown"><dt>Accommodation before markup</dt><dd>{money(q.baseCents/100)}</dd><dt>Markup</dt><dd>{money(q.markupCents/100)}</dd><dt>Accommodation with markup</dt><dd>{money(q.amounts.accommodation_cents/100)}</dd><dt>{q.discount.name} ({q.discount.bps/100}%)</dt><dd>−{money(q.amounts.discount_cents/100)}</dd><dt>Cleaning per stay</dt><dd>{money(q.amounts.cleaning_cents/100)}</dd><dt>Extra guest fees</dt><dd>{money(q.amounts.extra_guest_cents/100)}</dd></dl><p>Booking / quote date {q.quotedOn} · {q.leadDays} days before arrival · saved rule revision {q.ruleRevision||'defaults'}. This preview does not check availability or publish a channel rate.</p></div>;}
