import React,{useEffect,useState} from 'react';
import {propertySetup} from './property-setup.mjs';
import {ListingEditor} from './calendar-controls';
export function PropertySetup({data,user,busy,onAction,onNavigate,onRefresh,initialPropertyId,compact=false}){
 const [selected,setSelected]=useState(initialPropertyId||data.properties[0]?.id||''),[now,setNow]=useState(Date.now());
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(id);},[]);
 const rows=propertySetup(data,user.id,now),row=rows.find(r=>r.id===selected)||rows[0];
 if(!row)return <section className="panel"><span className="eyebrow">YOUR PROPERTY SETUP</span><h2>Add your first property</h2><p>Create a listing to set prices, prepare your guest TV and assign door locks.</p><button onClick={()=>onNavigate('overview')}>Add a listing in Overview</button></section>;
 return <section className="panel property-setup"><div className="stay-heading"><div><span className="eyebrow">YOUR PROPERTY SETUP</span><h2>{compact?'Finish property setup':'Set up each property'}</h2></div><button className="small" disabled={busy} onClick={onRefresh}>Refresh setup</button></div><p>Progress reflects saved settings in Treestand. Channel connections, online devices and installed guest codes require separate verification.</p><label className="setup-property">Property<select value={row.id} onChange={e=>setSelected(e.target.value)}>{rows.map(r=><option key={r.id} value={r.id}>{r.name} · {r.completed}/{r.total} steps saved</option>)}</select></label><div className="setup-progress"><div><strong>{row.completed} of {row.total} setup steps saved</strong><span>{row.next?`Next: ${row.next.title}`:'Saved setup complete · live connections still need verification'}</span></div><progress max={row.total} value={row.completed} aria-label={`${row.name} saved setup progress`}/></div>{compact?<><p>{row.next?.detail||'Review your property settings before preparing the next stay.'}</p><button onClick={()=>onNavigate('properties',row.id)}>Continue this property’s setup</button></>:<><div className="setup-grid">{row.steps.map((step,index)=><article className={`setup-step ${step.done?'setup-saved':''}`} key={step.id}><div className="stay-heading"><span className="setup-number">{index+1}</span><span className="badge">{step.done?'Saved':'Needs setup'}</span></div><h3>{step.title}</h3><p>{step.detail}</p>{step.id==='details'?<ListingEditor key={row.id+JSON.stringify(row.property)} property={row.property} busy={busy} onAction={onAction}/>:<button className="link" onClick={()=>onNavigate(step.tab,row.id)}>{step.action}</button>}</article>)}</div><div className="setup-extras"><div><h3>Make the TV feel like home</h3><p>{row.photos} uploaded {row.photos===1?'photo':'photos'} · Automatic music {row.musicEnabled?'enabled':'not enabled in saved settings'}. Add property photos, choose a tranquil soundtrack and preview the guest screen.</p></div><button className="small" onClick={()=>onNavigate('guest',row.id)}>Style this property’s TV</button></div><div className="setup-extras"><div><h3>Prepare for your first stay</h3><p>Add a confirmed manual booking, then review its welcome-screen and door-access preparation. Create cleaning and inspection tasks from Operations.</p></div><div className="task-actions"><button className="small" onClick={()=>onNavigate('bookings',row.id)}>Add a booking</button><button className="link" onClick={()=>onNavigate('operations',row.id)}>Open operations</button></div></div></>}</section>;
}
