import React,{useEffect,useRef,useState} from 'react';
import {Music,Play,Pause,Volume2} from 'lucide-react';
import {createMusicPlayer,musicChoices,musicVolume} from './tv-music.mjs';
export function TvMusic({defaultTrack='woodland',defaultVolume=15}){
 const [track,setTrack]=useState(musicChoices.some(option=>option.id===defaultTrack)?defaultTrack:'woodland'),[volume,setVolume]=useState(musicVolume(defaultVolume)),[playing,setPlaying]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[waitingForInput,setWaitingForInput]=useState(false);
 const player=useRef(null),request=useRef(0),mounted=useRef(true),guestPaused=useRef(false);
 function stop(){request.current++;player.current?.stop();setPlaying(false);setBusy(false);}
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;request.current++;player.current?.stop();};},[]);
 useEffect(()=>{function visibility(){if(document.hidden)stop();else if(!guestPaused.current)start(track,true);}document.addEventListener('visibilitychange',visibility);return()=>document.removeEventListener('visibilitychange',visibility);},[track,volume]);
 useEffect(()=>{const selected=musicChoices.some(option=>option.id===defaultTrack)?defaultTrack:'woodland';guestPaused.current=false;setTrack(selected);start(selected,true);},[defaultTrack]);
 useEffect(()=>{setVolume(musicVolume(defaultVolume));player.current?.volume(defaultVolume);},[defaultVolume]);
 async function start(selected=track,automatic=false){const attempt=++request.current;setBusy(true);setError('');setWaitingForInput(false);try{player.current ||= createMusicPlayer();const started=await player.current.play(selected,volume);if(mounted.current&&attempt===request.current){setPlaying(started);setBusy(false);setWaitingForInput(!started);}}catch(e){if(mounted.current&&attempt===request.current){setPlaying(false);setBusy(false);const unsupported=e.message?.includes('unavailable');setWaitingForInput(!unsupported);setError(automatic&&!unsupported?'Music is waiting for a remote input to enable sound.':e.message||'Music could not start. Try Play again.');}}}
 useEffect(()=>{if(!waitingForInput||busy||playing||guestPaused.current)return;function enable(e){if(!e.isTrusted)return;start(track,true);}window.addEventListener('pointerdown',enable);window.addEventListener('keydown',enable);return()=>{window.removeEventListener('pointerdown',enable);window.removeEventListener('keydown',enable);};},[waitingForInput,busy,playing,track,volume]);
 function toggle(){if(playing){guestPaused.current=true;setWaitingForInput(false);setError('');stop();}else{guestPaused.current=false;start();}}
 function choose(value){setTrack(value);if(playing)start(value);}
 return <div className="tv-music" aria-label="Tranquil music"><Music size={20}/><label className="sr-only" htmlFor="tv-music-choice">Music option</label><select id="tv-music-choice" value={track} disabled={busy} onChange={e=>choose(e.target.value)}>{musicChoices.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select><button className="tv-music-play" disabled={busy} onClick={toggle} aria-label={playing?'Pause tranquil music':'Play tranquil music'}>{playing?<Pause size={18}/>:<Play size={18}/>}<span>{busy?'Starting…':playing?'Pause':'Play'}</span></button><Volume2 size={18}/><label className="sr-only" htmlFor="tv-music-volume">Music volume</label><input id="tv-music-volume" type="range" min="0" max="40" step="1" value={volume} onChange={e=>{const value=musicVolume(e.target.value);setVolume(value);player.current?.volume(value);}}/><span className="tv-music-level">{volume}%</span>{error&&<span className="tv-music-error" role="status">{error}</span>}</div>;
}
