import React,{useEffect,useState} from 'react';
import {publicConnection} from './public-config';
export function TvPlayer(){
 const [token,setToken]=useState(()=>{const fragment=location.hash.slice(1);if(/^[0-9a-f]{64}$/.test(fragment)){localStorage.setItem('treestand-screen',fragment);history.replaceState(null,'',location.pathname+location.search);return fragment;}return localStorage.getItem('treestand-screen')||'';}),[content,setContent]=useState(null),[status,setStatus]=useState('Connecting…'),[code,setCode]=useState(''),[pairBusy,setPairBusy]=useState(false);
 useEffect(()=>{let active=true;let timer;let controller;async function refresh(){if(!token){setStatus('Enter the pairing code created in Guest Experience to connect this display.');return;}controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);try{
  const res=await fetch(`${import.meta.env.VITE_SUPABASE_URL||publicConnection.url}/functions/v1/guest-display`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store',signal:controller.signal});
  if(!res.ok)throw Error(res.status===401?'This screen link has expired or been revoked. Ask your host for a new link.':'Connection lost. Waiting to reconnect…');
  const data=await res.json();if(active){setContent(data);setStatus('');}
 }catch(e){if(active){setContent(null);setStatus(e.message||'Connection lost.');}}finally{clearTimeout(timeout);if(active)timer=setTimeout(refresh,60000);}}refresh();return()=>{active=false;controller?.abort();clearTimeout(timer);};},[token]);
 async function pair(e){e.preventDefault();setPairBusy(true);setStatus('Pairing…');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{
  const res=await fetch(`${import.meta.env.VITE_SUPABASE_URL||publicConnection.url}/functions/v1/guest-display`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code}),signal:controller.signal});
  const result=await res.json();if(!res.ok||!result.token)throw Error(result.error||'Pairing failed.');
  localStorage.setItem('treestand-screen',result.token);setToken(result.token);setCode('');
 }catch(e){setStatus(e.message||'Pairing failed.');}finally{clearTimeout(timer);setPairBusy(false);}}
 function disconnect(){localStorage.removeItem('treestand-screen');setToken('');setContent(null);}
 return <main className="tv-player"><div className="tv-brand"><img src={`${import.meta.env.BASE_URL}brand/treestand-logo.webp`} alt="Treestand Manager" width="1200" height="400"/><span>WELCOME</span></div>{status&&<p role="status">{status}</p>}{!token&&<form className="tv-pair-form" onSubmit={pair}><label>Pairing code<input required value={code} maxLength="32" autoComplete="off" autoCapitalize="characters" onChange={e=>setCode(e.target.value)} placeholder="XXXX-XXXX-XXXX-XXXX"/></label><button disabled={pairBusy}>{pairBusy?'Pairing…':'Connect screen'}</button></form>}{content&&<><div className="eyebrow">{content.property.name}</div><h1>{content.display.title.replaceAll('{{guest}}','Guest')}</h1><p className="tv-intro">{content.display.welcome}</p><div className="guest-times"><span>Check-in {content.property.check_in.slice(0,5)}</span><span>Check-out {content.property.check_out.slice(0,5)}</span></div><div className="tv-sections">{[['Your house guide','guidebook'],['Explore nearby','recommendations'],['Need a hand?','contact']].map(([title,key])=>content.display[key]&&<article key={key}><h2>{title}</h2><p>{content.display[key]}</p></article>)}</div></>}<div className="tv-controls"><button onClick={()=>document.documentElement.requestFullscreen?.().catch(()=>{})}>Full screen</button><button onClick={disconnect}>Disconnect this screen</button></div></main>;
}
