import React,{useEffect,useState,useRef} from 'react';
import {publicConnection} from './public-config';
import {normalizePairingCode,isPairingCode} from './pairing-code.mjs';
export function TvPlayer(){
 const [token,setToken]=useState(()=>{const fragment=location.hash.slice(1);if(/^[0-9a-f]{64}$/.test(fragment)){localStorage.setItem('treestand-screen',fragment);history.replaceState(null,'',location.pathname+location.search);return fragment;}return localStorage.getItem('treestand-screen')||'';}),[content,setContent]=useState(null),[status,setStatus]=useState('Connecting…'),[code,setCode]=useState(''),[pairBusy,setPairBusy]=useState(false);
 const codeInputs=useRef([]);
 function changeGroup(index,value){const cleaned=normalizePairingCode(value);if(cleaned.length>4)return;const groups=Array.from({length:4},(_,i)=>code.slice(i*4,i*4+4));groups[index]=cleaned;setCode(groups.map(group=>group.padEnd(4,' ')).join(''));if(cleaned.length===4&&index<3)codeInputs.current[index+1]?.focus();}
 function pasteCode(e){const pasted=normalizePairingCode(e.clipboardData.getData('text'));if(pasted.length<=4)return;e.preventDefault();if(pasted.length!==16){setStatus('A pairing code has four groups of four characters. Check the code or create a new one.');return;}setCode(pasted);codeInputs.current[3]?.focus();}

 useEffect(()=>{let active=true;let timer;let controller;async function refresh(){if(!token){setStatus('Enter the pairing code created in Guest Experience to connect this display.');return;}controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);try{
  const res=await fetch(`${import.meta.env.VITE_SUPABASE_URL||publicConnection.url}/functions/v1/guest-display`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store',signal:controller.signal});
  if(!res.ok)throw Error(res.status===401?'This screen link has expired or been revoked. Ask your host for a new link.':'Connection lost. Waiting to reconnect…');
  const data=await res.json();if(active){setContent(data);setStatus('');}
 }catch(e){if(active){setContent(null);setStatus(e.message||'Connection lost.');}}finally{clearTimeout(timeout);if(active)timer=setTimeout(refresh,60000);}}refresh();return()=>{active=false;controller?.abort();clearTimeout(timer);};},[token]);
 async function pair(e){e.preventDefault();const normalized=normalizePairingCode(code);if(!isPairingCode(normalized)){setStatus('Enter all 16 letters and numbers. Dashes and spaces are not needed.');return;}setPairBusy(true);setStatus('Pairing…');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{
  const res=await fetch(`${import.meta.env.VITE_SUPABASE_URL||publicConnection.url}/functions/v1/guest-display`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:normalized}),signal:controller.signal});
  const result=await res.json();if(!res.ok||!result.token)throw Error(result.error||'Pairing failed.');
  localStorage.setItem('treestand-screen',result.token);setToken(result.token);setCode('');
 }catch(e){setStatus(e.message||'Pairing failed.');}finally{clearTimeout(timer);setPairBusy(false);}}
 function disconnect(){localStorage.removeItem('treestand-screen');setToken('');setContent(null);}
 return <main className="tv-player"><div className="tv-brand"><img src={`${import.meta.env.BASE_URL}brand/treestand-logo.webp`} alt="Treestand Manager" width="1200" height="400"/><span>WELCOME</span></div>{status&&<p role="status">{status}</p>}{!token&&<form className="tv-pair-form" onSubmit={pair}><fieldset className="pairing-fields"><legend>Pairing code</legend><div className="pairing-groups">{[0,1,2,3].map(index=><React.Fragment key={index}>{index>0&&<span className="pairing-dash" aria-hidden="true">–</span>}<input ref={el=>codeInputs.current[index]=el} aria-label={`Pairing code group ${index+1} of 4`} aria-describedby="pairing-help" required value={code.slice(index*4,index*4+4).trim()} maxLength="4" minLength="4" size="4" autoComplete="off" autoCorrect="off" spellCheck={false} autoCapitalize="characters" onChange={e=>changeGroup(index,e.target.value)} onPaste={pasteCode} placeholder="XXXX" onKeyDown={e=>{if(e.key==='Backspace'&&!e.currentTarget.value&&index>0)codeInputs.current[index-1]?.focus();}}/></React.Fragment>)}</div></fieldset><p id="pairing-help">Enter four characters in each box. The dashes are already included. New codes contain neither zero (0) nor the letter O. Codes expire after 30 minutes and work once.</p><button disabled={pairBusy}>{pairBusy?'Pairing…':'Connect screen'}</button></form>}{content&&<><div className="eyebrow">{content.property.name}</div><h1>{content.display.title.replaceAll('{{guest}}','Guest')}</h1><p className="tv-intro">{content.display.welcome}</p><div className="guest-times"><span>Check-in {content.property.check_in.slice(0,5)}</span><span>Check-out {content.property.check_out.slice(0,5)}</span></div><div className="tv-sections">{[['Your house guide','guidebook'],['Explore nearby','recommendations'],['Need a hand?','contact']].map(([title,key])=>content.display[key]&&<article key={key}><h2>{title}</h2><p>{content.display[key]}</p></article>)}</div></>}<div className="tv-controls"><button onClick={()=>document.documentElement.requestFullscreen?.().catch(()=>{})}>Full screen</button><button onClick={disconnect}>Disconnect this screen</button></div></main>;
}
